Add loop functionality to run over a time period and clean the script up a bit

diff --git a/ci/utility/corporate-storage-coalescence/meta-corporate-storage-coalescence.yml b/ci/utility/corporate-storage-coalescence/meta-corporate-storage-coalescence.yml
--- a/ci/utility/corporate-storage-coalescence/meta-corporate-storage-coalescence.yml
+++ b/ci/utility/corporate-storage-coalescence/meta-corporate-storage-coalescence.yml
@@ -22,39 +22,71 @@ meta-corporate-storage-coalescence:
               source /assume-role
               set +x
 
-              echo "Setting corporate storage values which apply to all storage types"
-              date_to_run=$(date -d "${DATE_TO_RUN_ON}" +"%y/%M/%d")
-              s3_bucket_id=$(cat ../terraform-output-ingest/outputs.json | jq -r '.corporate_storage_bucket.value.id')
-              echo "Set date_to_run to '${date_to_run}' and s3_bucket_id to '${s3_bucket_id}'"
-              
-              echo "Setting corporate storage values for given storage type"
+              function execute_coalesce {
+                local date_to_run=$(date -d "$1" +'%Y/%m/%d')
+                local full_prefix="${S3_BASE_PREFIX}/${date_to_run}/"
 
-              if [[ "${CORPORATE_STORAGE_TYPE}" == "equalities" ]]; then
-                echo "Setting equalities corporate storage values"
-                s3_base_prefix=$(cat ../terraform-output-ingest/outputs.json | jq -r '.corporate_data_loader.value.s3_base_prefix_equalities')
-                max_size_files=$(cat ../terraform-output-ingest-consumers/outputs.json | jq -r '.k2hb_corporate_storage_coalesce_values.value.max_size_files.equalities')
-                max_size_bytes=$(cat ../terraform-output-ingest-consumers/outputs.json | jq -r '.k2hb_corporate_storage_coalesce_values.value.max_size_bytes.equalities')
-              elif [[ "${CORPORATE_STORAGE_TYPE}" == "audit" ]]; then
-                echo "Setting audit corporate storage values"
-                s3_base_prefix=$(cat ../terraform-output-ingest/outputs.json | jq -r '.corporate_data_loader.value.s3_base_prefix_audit')
-                max_size_files=$(cat ../terraform-output-ingest-consumers/outputs.json | jq -r '.k2hb_corporate_storage_coalesce_values.value.max_size_files.audit')
-                max_size_bytes=$(cat ../terraform-output-ingest-consumers/outputs.json | jq -r '.k2hb_corporate_storage_coalesce_values.value.max_size_bytes.audit')
-              elif [[ "${CORPORATE_STORAGE_TYPE}" == "main" ]]; then
-                echo "Setting main corporate storage values"
-                s3_base_prefix=$(cat ../terraform-output-ingest/outputs.json | jq -r '.corporate_data_loader.value.s3_base_prefix_ucfs')
-                max_size_files=$(cat ../terraform-output-ingest-consumers/outputs.json | jq -r '.k2hb_corporate_storage_coalesce_values.value.max_size_files.main')
-                max_size_bytes=$(cat ../terraform-output-ingest-consumers/outputs.json | jq -r '.k2hb_corporate_storage_coalesce_values.value.max_size_bytes.main')
-              else
-                echo "Unrecognised corporate storage type of '${CORPORATE_STORAGE_TYPE}'"
-                exit 1
-              fi
+                echo "Running coalesce for date of '${date_to_run}' and prefix of '${full_prefix}'"
+                python main.py -b "${S3_BUCKET_ID}" -f "${MAX_SIZE_FILES}" -s "${MAX_SIZE_BYTES}" -p "${full_prefix}"
+                local result=$?
 
-              echo "Set s3_base_prefix to '${s3_base_prefix}', max_size_files to '${max_size_files}' and max_size_bytes to '${max_size_bytes}'"
+                echo "Checking result of coalesce"
+                if [ ! $result -eq 0 ]; then
+                    echo "Exiting with error due to failed coalesce with exit code of '$result'"
+                    exit 1
+                else
+                    echo "Coalesce successful"
+                fi
+              }
 
-              full_s3_prefix="${s3_base_prefix}/${date_to_run}/"
-              echo "Set full_s3_prefix to '${full_s3_prefix}'"
-            
-              python main.py -b "${s3_bucket_id}" -f "${max_size_files}" -s "${max_size_bytes}" -p "${full_s3_prefix}"
+              function set_storage_type_values {
+                echo "Setting corporate storage values for given storage type"
+
+                if [[ "${CORPORATE_STORAGE_TYPE}" == "equalities" ]]; then
+                  echo "Setting equalities corporate storage values"
+                  export S3_BASE_PREFIX=$(cat ../terraform-output-ingest/outputs.json | jq -r '.corporate_data_loader.value.s3_base_prefix_equalities')
+                  export MAX_SIZE_FILES=$(cat ../terraform-output-ingest-consumers/outputs.json | jq -r '.k2hb_corporate_storage_coalesce_values.value.max_size_files.equalities')
+                  export MAX_SIZE_BYTES=$(cat ../terraform-output-ingest-consumers/outputs.json | jq -r '.k2hb_corporate_storage_coalesce_values.value.max_size_bytes.equalities')
+                elif [[ "${CORPORATE_STORAGE_TYPE}" == "audit" ]]; then
+                  echo "Setting audit corporate storage values"
+                  export S3_BASE_PREFIX=$(cat ../terraform-output-ingest/outputs.json | jq -r '.corporate_data_loader.value.s3_base_prefix_audit')
+                  export MAX_SIZE_FILES=$(cat ../terraform-output-ingest-consumers/outputs.json | jq -r '.k2hb_corporate_storage_coalesce_values.value.max_size_files.audit')
+                  export MAX_SIZE_BYTES=$(cat ../terraform-output-ingest-consumers/outputs.json | jq -r '.k2hb_corporate_storage_coalesce_values.value.max_size_bytes.audit')
+                elif [[ "${CORPORATE_STORAGE_TYPE}" == "main" ]]; then
+                  echo "Setting main corporate storage values"
+                  export S3_BASE_PREFIX=$(cat ../terraform-output-ingest/outputs.json | jq -r '.corporate_data_loader.value.s3_base_prefix_ucfs')
+                  export MAX_SIZE_FILES=$(cat ../terraform-output-ingest-consumers/outputs.json | jq -r '.k2hb_corporate_storage_coalesce_values.value.max_size_files.main')
+                  export MAX_SIZE_BYTES=$(cat ../terraform-output-ingest-consumers/outputs.json | jq -r '.k2hb_corporate_storage_coalesce_values.value.max_size_bytes.main')
+                else
+                  echo "Unrecognised corporate storage type of '${CORPORATE_STORAGE_TYPE}'"
+                  exit 1
+                fi
+
+                echo "Set S3_BASE_PREFIX to '${S3_BASE_PREFIX}', MAX_SIZE_FILES to '${MAX_SIZE_FILES}' and MAX_SIZE_BYTES to '${MAX_SIZE_BYTES}'"
+              }
+
+              function set_global_storage_values {
+                echo "Setting corporate storage values which apply to all storage types"
+                export FIRST_DATE_TO_RUN=$(date -d "${START_DATE}" +"%y%M%d")
+
+                if [[ -z "${END_DATE}" ]]; then
+                  export LAST_DATE_TO_RUN="${FIRST_DATE_TO_RUN}"
+                else
+                  export LAST_DATE_TO_RUN=$(date -d "${END_DATE}" +"%y%M%d")
+                fi
+
+                export S3_BUCKET_ID=$(cat ../terraform-output-ingest/outputs.json | jq -r '.corporate_storage_bucket.value.id')
+                echo "Set FIRST_DATE_TO_RUN to '${FIRST_DATE_TO_RUN}', LAST_DATE_TO_RUN to '${LAST_DATE_TO_RUN}' and S3_BUCKET_ID to '${S3_BUCKET_ID}'"
+              }
+
+              set_global_storage_values
+              set_storage_type_values
+
+              current_date_to_run="${FIRST_DATE_TO_RUN}"
+              while [ ${current_date_to_run} -le ${LAST_DATE_TO_RUN} ]; do
+                execute_coalesce "${current_date_to_run}"
+                current_date_to_run=$(date -d "${current_date_to_run}+1 day")
+              done
         inputs:
           - name: dataworks-corporate-storage-coalescence
           - name: meta
