Bash batches (#60)
* Allow running in batches within bash according to partition number

* Update to pass partition count

* Fix the loop

* Fix the loop

diff --git a/ci/utility/corporate-storage-coalescence/meta-corporate-storage-coalescence.yml b/ci/utility/corporate-storage-coalescence/meta-corporate-storage-coalescence.yml
--- a/ci/utility/corporate-storage-coalescence/meta-corporate-storage-coalescence.yml
+++ b/ci/utility/corporate-storage-coalescence/meta-corporate-storage-coalescence.yml
@@ -37,19 +37,26 @@ meta-corporate-storage-coalescence:
 
               function run_script {
                 local prefix="${1}"
-                python main.py -b "${S3_BUCKET_ID}" -f "${MAX_SIZE_FILES}" -s "${MAX_SIZE_BYTES}" -p "${prefix}" -t "${THREAD_COUNT}"
+                local partition="${2}"
+
+                if [[ ! -z "${partition} "]]; then
+                  local partition_param=" -n ${partition}"
+                fi
+
+                python main.py -b "${S3_BUCKET_ID}" -f "${MAX_SIZE_FILES}" -s "${MAX_SIZE_BYTES}" -p "${prefix}" -t "${THREAD_COUNT}""${partition_param}"
                 local result=$?
 
                 echo "Checking result of coalesce"
                 if [ $result -eq $EXIT_CODE_FOR_CREDENTIALS_ERROR ] && [ "${AUTO_RERUN_ON_CRENDENTIALS_TIMEOUT}" -eq "true" ]; then
                     echo "Assuming credentials again and re-running script due to exit code of '$result' and auto-run setting of '${AUTO_RERUN_ON_CRENDENTIALS_TIMEOUT}'"
                     source /assume-role
-                    run_script "${prefix}"
+                    run_script "${prefix}" "${partition}"
                 elif [ ! $result -eq 0 ]; then
                     echo "Exiting with error due to failed coalesce with exit code of '$result' and auto-run setting of '${AUTO_RERUN_ON_CRENDENTIALS_TIMEOUT}'"
                     exit 1
                 else
                     echo "Coalesce successful"
+                    exit 0
                 fi
               }
 
@@ -59,7 +66,39 @@ meta-corporate-storage-coalescence:
 
                 echo "Running coalesce for bucket of '${S3_BUCKET_ID}', file max of '${MAX_SIZE_FILES}', size max of '${MAX_SIZE_BYTES}', prefix of '${full_prefix}' and thread count of '${THREAD_COUNT}'"
 
-                run_script "${full_prefix}"
+                if [[ -z "${RUN_IN_PARTITION_BATCHES_OF_THIS_SIZE}" ]]; then
+                  run_script "${full_prefix}" &
+                  wait $!
+                  exit $?
+                else
+                  partitions=($(seq 0 19))
+                  for ((i=0; i<${#partitions[@]}; i+=RUN_IN_PARTITION_BATCHES_OF_THIS_SIZE)); do
+                      pids=""
+                      FAILURE_COUNT=0
+
+                      for partition_count in "${partitions[@]:i:i+RUN_IN_PARTITION_BATCHES_OF_THIS_SIZE}"; do
+                        run_script "${full_prefix}" "${partition_count}" &
+                        pids="$pids $!"
+                      done
+                      
+                      echo "Waiting for all executions in batch to finish"
+
+                      for pid in $pids; do
+                        wait $pid
+                        if [ ! $? -eq 0 ]; then
+                          ((FAILURE_COUNT=FAILURE_COUNT+1))
+                        fi
+                      done
+                      
+                      echo "Checking results of batch"
+
+                      if [[ $FAILURE_COUNT -gt 0 ]]; then
+                        echo "Exiting abnormally due to '$FAILURE_COUNT' failed executions in batch starting with count of '$partition_count'"
+                        exit 1
+                      fi
+                      
+                      echo "Batch succeeded"
+                  done
               }
 
               function set_storage_type_values {
